### ISSUE TITLE
Scanning blocks assertion failure

### ISSUE THREAD

**Issue by cygnet3** [cygnet3/sp-client#22]
assertion failed: *range.end() <= self.filters.height()

Seems to happen when a new block gets confirmed. For some reason we are aware that the block height is +1 larger, but the filters height is not updating along with it

**Comment by vincenzopalazzo** [comment]
>Seems to happen when a new block gets confirmed. For some reason we are aware that the block height is +1 larger, but the filters height is not updating along with it

I am not sure that this happens only when a new block is confirmed, but I think this is the right vision of it.

**Comment by cygnet3** [comment]
We currently rely on blindbit so this issue is outdated.
